project:
  type: website
  output-dir: docs

website:
  title: "Deepanshu Mahto"
  navbar:
    logo: images/logo.png
    # right:
      # - icon: twitter
      #   href: https://twitter.com/deepanshumahto
      # - icon: linkedin
      #   href: https://www.linkedin.com/in/mahtodeepanshu/
      # - icon: github
      #   href: https://github.com/mahtodeepanshu
    left:
      - href: index.qmd
        text: Home
  page-footer:
    center: 
      - text: "Built with ❤️ &copy; 2023 Deepanshu Mahto"
        href: license.qmd
  favicon: images/logo.png
  twitter-card: true
  comments: false

format:
  html:
    theme: #cosmo #darkly #pulse #skectchy #superhero 
      light: [cosmo, theme-light.scss]
      # dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



